
/* autogenerated by Processing revision 1282 on 2022-03-18 */
import backgrounds.BackgroundBuilder;
import messages.MessageBuilder;
import processing.core.PApplet;
import providerManagers.ProviderManager;
import safeTextZones.TextBuilder;

public class WallpaperBuilder extends PApplet {

	// these should become managers so they can rotate if needed
	private ProviderManager<MessageBuilder> messageGeneratorManager;
	private ProviderManager<BackgroundBuilder> backgroundBuilderManager;
	private  ProviderManager<TextBuilder> textBuilderManager;

	public WallpaperBuilder() {
		System.out.println("constructor!");
		messageGeneratorManager = GodClass.getMessageBuilderManager();
		backgroundBuilderManager = GodClass.getBackgroundBuilderManager();
		textBuilderManager = GodClass.getTextBuilderManager();
	}
//
//int width = 1284;
//int height = 2778;

	int widthBuffer = 100;
	int heightBuffer = 200;

	public void setup() {
		System.out.println("setup!");
		background(255);
		noLoop();
	}

	public void settings() {
		size(1284 / 3, 2778 / 3);
	}

	public void draw() {
		/*
		 * TODOs:
		 * 
		 * Get Message
		 * 
		 * Choose color themes Doodles? if yes, get them? Draw background
		 * 
		 */

		System.out.println("draw!");
//	fill(255);
//	rect(50,50,100,100);
//	
//	translate(200,200);
		backgroundBuilderManager.getBuilder().drawBackground(this);
		String message = messageGeneratorManager.getBuilder().getRandomMessage();
		textBuilderManager.getBuilder().addText(this, message);
//		textAlign(CENTER);
//		text(messageGeneratorManager.getBuilder().getRandomMessage(), 50, 50);
	}

}
